table DimDate
	lineageTag: 93caf607-363c-4850-8f7d-d5437726b549

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: d072832c-1ddb-453d-b683-57b700ff7e1f
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 75877bff-8a02-428d-8c2d-8db3fa38dfe1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayOfWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 41e0e1eb-4814-47fb-b390-83c548367967
		summarizeBy: none
		sourceColumn: DayOfWeekNumber

		annotation SummarizationSetBy = Automatic

	column DayOfWeekName
		dataType: string
		lineageTag: 40330613-c8a2-412d-a8f8-976ec99fc637
		summarizeBy: none
		sourceColumn: DayOfWeekName

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4f546d43-f4b7-4d32-a8f1-23c950a5a057
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNumber

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: c17f2972-17c2-4143-b183-4c792ee1b4ed
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fc904d74-c2bb-4807-b6d3-3700f97c027e
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthYearName
		dataType: string
		lineageTag: 5c567ffb-096e-4191-867c-9b39523748e1
		summarizeBy: none
		sourceColumn: MonthYearName

		annotation SummarizationSetBy = Automatic

	column MonthYearNumber
		dataType: int64
		formatString: 0
		lineageTag: 37fed594-5001-455f-aa4f-f9d10af201fe
		summarizeBy: none
		sourceColumn: MonthYearNumber

		annotation SummarizationSetBy = Automatic

	column MonthNameInitial
		dataType: string
		lineageTag: 5dc1b609-25ef-43f5-a2ec-e58b5d050b0b
		summarizeBy: none
		sourceColumn: MonthNameInitial

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Sql.Database(server, database),
				    Custom1 = Source{[Name="DimDate"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Custom1,{"DateKey", "FullDateAlternateKey", "DayNumberOfWeek", "EnglishDayNameOfWeek", "EnglishMonthName", "MonthNumberOfYear", "CalendarYear"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"FullDateAlternateKey", "Date"}, {"DayNumberOfWeek", "DayOfWeekNumber"}, {"EnglishDayNameOfWeek", "DayOfWeekName"}, {"EnglishMonthName", "MonthName"}, {"MonthNumberOfYear", "MonthNumber"}, {"CalendarYear", "Year"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [DateKey] >= 20101229 and [DateKey] <= 20140209),
				    #"MonthYearName Added" = Table.AddColumn(#"Filtered Rows", "MonthYearName", each Date.ToText([Date], "MMM yy", "en-US"), type text),
				    #"MonthYearNumber Added" = Table.AddColumn(#"MonthYearName Added", "MonthYearNumber", each [Year] * 100 + [MonthNumber], Int64.Type),
				    #"MonthNameInitial Added" = Table.AddColumn(#"MonthYearNumber Added", "MonthNameInitial", each let
				  rept_times = 12 - [MonthNumber],
				  initial = Text.Start([MonthName], 1)
				in
				  Text.Repeat(Character.FromNumber(8203), rept_times) & initial, type text)
				in
				    #"MonthNameInitial Added"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

