table DimProducts
	lineageTag: a8d97f73-f188-4ef7-891c-27e6a881f653

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 7e5213a1-b7a8-4e83-b5b9-c1f3e28debe4
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: ceb78190-08d3-49e8-b3ea-60e44e13b851
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: f1101f4b-67ef-451e-ad8c-861bb86d0a0c
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 269e4c74-d529-4d6b-b2df-385358c363cd
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ModelName
		dataType: string
		lineageTag: f0088cc4-91e0-47e9-90bb-bfae5c231b2b
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column LargePhoto
		dataType: string
		lineageTag: dde5a670-2d66-43c0-81d7-1d5ef34e17fa
		summarizeBy: none
		sourceColumn: LargePhoto

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryName
		dataType: string
		lineageTag: 3f5232b4-6cf6-4804-b4b1-57053e539997
		summarizeBy: none
		sourceColumn: ProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryName
		dataType: string
		lineageTag: ca567801-f6d0-430e-974d-cbd181edc84f
		summarizeBy: none
		sourceColumn: ProductCategoryName

		annotation SummarizationSetBy = Automatic

	column ImageURL = ```
			"data:image/png;base64," & 'DimProducts'[LargePhoto] 
			```
		lineageTag: 2bc59e15-4b88-46c7-85ad-e9e45fccab24
		dataCategory: ImageUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DimProducts = m
		mode: import
		source =
				let
				    Source = Sql.Database(server, database),
				    Custom1 = Source{[Name="DimProduct"]}[Data],
				    #"Expanded DimProductSubcategory" = Table.ExpandRecordColumn(Custom1, "DimProductSubcategory", {"EnglishProductSubcategoryName", "DimProductCategory"}, {"EnglishProductSubcategoryName", "DimProductCategory"}),
				    #"Expanded DimProductCategory" = Table.ExpandRecordColumn(#"Expanded DimProductSubcategory", "DimProductCategory", {"EnglishProductCategoryName"}, {"EnglishProductCategoryName"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded DimProductCategory",{"FactInternetSales", "FactResellerSales"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"ProductKey", "EnglishProductName", "Color", "Weight", "ModelName", "LargePhoto", "EnglishProductSubcategoryName", "EnglishProductCategoryName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"EnglishProductName", "ProductName"}, {"EnglishProductSubcategoryName", "ProductSubcategoryName"}, {"EnglishProductCategoryName", "ProductCategoryName"}}),
				    #"LargePhoto Decripted" = Table.TransformColumns(#"Renamed Columns", {{"LargePhoto", each if _ <> null then Binary.ToText(_, BinaryEncoding.Base64) else null, type text}})
				in
				    #"LargePhoto Decripted"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

