table DimSalesTerritory
	lineageTag: 35e06399-7236-4038-a40e-53a21441e419

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 5f511f39-be88-4674-aa6f-2246ed690c9f
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryRegion
		dataType: string
		lineageTag: 3cfe8476-b56a-425c-ba59-ec113987ae39
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: SalesTerritoryRegion

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryCountry
		dataType: string
		lineageTag: a906882e-f6d8-4372-9c07-d8a362b5afc5
		dataCategory: Country
		summarizeBy: none
		sourceColumn: SalesTerritoryCountry

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryGroup
		dataType: string
		lineageTag: 8eb2b68f-78d3-4c15-8ab1-1f3cb9e75790
		summarizeBy: none
		sourceColumn: SalesTerritoryGroup

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryImage
		dataType: string
		lineageTag: 51c1330e-3e94-4d2f-9932-141df70d348b
		summarizeBy: none
		sourceColumn: SalesTerritoryImage

		annotation SummarizationSetBy = Automatic

	partition DimSalesTerritory = m
		mode: import
		source =
				let
				    Source = Sql.Database(server, database),
				    Custom1 = Source{[Name="DimSalesTerritory"]}[Data],
				    #"SalesTerritoryImage Decripted" = Table.TransformColumns(Custom1, {{"SalesTerritoryImage", each if _ <> null then Binary.ToText(_, BinaryEncoding.Base64) else null, type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"SalesTerritoryImage Decripted",{"SalesTerritoryKey", "SalesTerritoryRegion", "SalesTerritoryCountry", "SalesTerritoryGroup", "SalesTerritoryImage"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

