table DimCustomer
	lineageTag: 632f6612-10b9-4caf-85f1-bd2c3e84356b

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: a58de883-c231-44a5-8bf9-1f8ec6aa1ebb
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: a6a188e4-2fe8-4757-8c9e-c3c2765817d8
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4bfe8518-daa1-4ee3-b7b5-46e6fea1a9c6
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 173f4f0f-f491-4566-bbfe-c8390bf219b8
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: d31fd633-f38a-498a-a2ac-ca11738023d4
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EnglishOccupation
		dataType: string
		lineageTag: 1537ef77-e0be-4320-b37a-696b197128e9
		summarizeBy: none
		sourceColumn: EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: string
		lineageTag: 7cd76869-cb4c-4b61-86c5-0b7bfb4ec270
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: d1ec34d2-f0db-4a82-b62c-6a191ecff1f8
		summarizeBy: none
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 85a5d43e-3fcd-41fe-9ab0-d0edd4d8670c
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column StateProvinceName
		dataType: string
		lineageTag: 07201c0c-ac64-475d-bb55-7b2999d4c52f
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: StateProvinceName

		annotation SummarizationSetBy = Automatic

	column CountryRegionName
		dataType: string
		lineageTag: 7f365fbb-ff1e-42b9-9c03-abeafb049da2
		dataCategory: Country
		summarizeBy: none
		sourceColumn: CountryRegionName

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		source =
				let
				    Source = Sql.Database(server, database),
				    Custom1 = Source{[Name="DimCustomer"]}[Data],
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(Custom1, "DimGeography", {"City", "StateProvinceName", "EnglishCountryRegionName"}, {"City", "StateProvinceName", "EnglishCountryRegionName"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Expanded DimGeography", "CustomerName", each Text.Combine({[FirstName], [MiddleName], [LastName]}, " "), type text),
				    #"Removed Other Columns" = Table.SelectColumns(#"Inserted Merged Column",{"CustomerKey", "CustomerName", "BirthDate", "MaritalStatus", "Gender", "EnglishOccupation", "HouseOwnerFlag", "NumberCarsOwned", "City", "StateProvinceName", "EnglishCountryRegionName"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"EnglishCountryRegionName", "CountryRegionName"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

